#!/bin/sh

Mashelp(){
echo "`basename $0` help            显示用法"
echo "`basename $0` version         显示MAS版本号"
echo "`basename $0` status          显示所有模块的模块名和模块状态"
echo "`basename $0` start [mid]     启动模块名为[mid]的模块,若缺省或为all则启动所有业务模块"
echo "`basename $0` stop  [mid]     停止模块名[mid]的模块,若缺省或为all则停止所有业务模块"        
echo "`basename $0` restart [mid]   重启模块名[mid]的模块,若缺省或为all则启动所有业务模块"

}

#出错时显示的帮助
CommondError()
{
    echo "Try 'mas help' for more information."
}

#得到mas版本号
MasVersion(){
   if [ -f $MAS_HOME/eieconfig.xml ]; then 
      bb=`cat $MAS_HOME/eieconfig.xml|grep EIEVersion`
      cc=`echo ${bb##*<EIEVersion>}`
      echo ${cc%%</EIEVersion>*}
   else
      echo "version file lost"
   fi
}



#得到mas状态
MasStatus(){

    black=""
    secode_black="                   "
    echo "***********************************************************************"
    
    if ps -fu `whoami`|grep -E mtm.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black mtm      $secode_black[ON]"
    else
      echo "$black mtm      $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E masagent.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black masagent $secode_black[ON]"
    else
      echo "$black masagent $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E bootstrap.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black was      $secode_black[ON]"
    else
      echo "$black was      $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E eies.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black sms      $secode_black[ON]"
    else
      echo "$black sms      $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E eup.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black eup      $secode_black[ON]"
    else
      echo "$black eup      $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E mms.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black mms      $secode_black[ON]"
    else
      echo "$black mms      $secode_black[OFF]"
    fi
    
    if ps -fu `whoami`|grep -E sps.jar|grep -E java >/dev/null 2>&1 ;then 
      echo "$black sps      $secode_black[ON]"
    else
      echo "$black sps      $secode_black[OFF]"
    fi
    
#    if ps -fu `whoami`|grep -E mon.jar|grep -E java >/dev/null 2>&1 ;then 
#      echo "$black mon      $secode_black[ON]"
#    else
#      echo "$black mon      $secode_black[OFF]"
#    fi
    
    echo "***********************************************************************"

#echo "                CUP Message"
# cat /proc/cpuinfo|grep "model name"
# sar 1 1
#
#echo ""
#    echo "***********************************************************************"
#echo "                Memory Message"
#echo "memory total:$(free |grep Mem |awk '{print $2/1024}')M"
#
#echo ""
#    echo "***********************************************************************"
#echo "                Hard Disk Message"
#df -h 
#
}

#------------------------------------------MTM-------------------------------------------------
#mtm启动
MtmStart(){
   if ps -fu `whoami`|grep -E mtm.jar|grep -E java >/dev/null 2>&1 ;then
      echo "mtm exist"
   else
     if [ -f $MAS_HOME/mtm/mtm.jar ] 
     then
       echo 'begin to start mtm: java -jar mtm.jar'
       cd $MAS_HOME/mtm
       java -jar mtm.jar  >/dev/null 2>&1 &
     else
       echo "mtm.jar not exist,start failed"
     fi
   fi
}

#mtm停止
MtmStop()
{
   echo "begin to close mtm"
   ps -fu `whoami` | grep -E "mtm.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}

#------------------------------------------masagent-------------------------------------------------
#masagent启动
MasagentStart(){
   if ps -fu `whoami`|grep -E masagent.jar|grep -E java >/dev/null 2>&1 ;then
      echo "masagent exist"
   else
     if [ -f $MAS_HOME/masagent/masagent.jar ] 
     then
       echo 'begin to start masagent: java -jar masagent.jar'
       cd $MAS_HOME/masagent/
       java -jar masagent.jar  >/dev/null 2>&1 &
     else
       echo "masagent.jar not exist,start failed"
     fi
   fi
}

#masagent停止
MasagentStop()
{
   echo "begin to close masagent"
   ps -fu `whoami` | grep -E "masagent.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}

#------------------------------------------WAS-------------------------------------------------
#was启动
WasStart(){
   if ps -fu `whoami`|grep -E bootstrap.jar|grep -E java >/dev/null 2>&1 ;then
      echo "was exist"
   else
     if [ -f $MAS_HOME/opt/tomcat/bin/startup.sh ] 
     then
       echo "begin to start was"
       cd $MAS_HOME/opt/tomcat/bin
       ./startup.sh
     else
       echo "startup.sh not exist,start failed"
     fi
   fi
}

#Was停止
WasStop()
{
   echo "begin to close was"
   ps -fu `whoami` | grep -E "bootstrap.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}


#------------------------------------------SMS-------------------------------------------------
#SMS启动
SmsStart(){
   if ps -fu `whoami`|grep -E eies.jar|grep -E java >/dev/null 2>&1 ;then
      echo "sms exist"
   else
     if [ -f $MAS_HOME/sms/eies.jar ] 
     then
       echo 'begin to start sms:java -Xmx512m -Xms64m -jar eies.jar'
       cd $MAS_HOME/sms/
       java -Xmx512m -Xms64m -jar eies.jar  >/dev/null 2>&1 &
     else
       echo "eies.jar not exist,start failed"
     fi
   fi
}

#sms停止
SmsStop()
{
   echo "begin to close sms"
   ps -fu `whoami` | grep -E "eies.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}

#------------------------------------------EUP-------------------------------------------------
#Eup启动
EupStart(){
   if ps -fu `whoami`|grep -E eup.jar|grep -E java >/dev/null 2>&1 ;then
      echo "eup exist"
   else
     if [ -f $MAS_HOME/eup/eup.jar ] 
     then
       echo 'begin to start eup:java -jar eup.jar'
       cd $MAS_HOME/eup/
       java -jar eup.jar  >/dev/null 2>&1 &
     else
       echo "eup.jar not exist,start failed"
     fi
   fi
}

#Eup停止
EupStop()
{
   echo "begin to close eup"
   ps -fu `whoami` | grep -E "eup.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}

#------------------------------------------MMS-------------------------------------------------
#彩信启动
MmsStart(){
   if ps -fu `whoami`|grep -E mms.jar|grep -E java >/dev/null 2>&1 ;then
      echo "mms exist"
   else
     if [ -f $MAS_HOME/mms/mms.jar ] 
     then
       echo 'begin to start mms: java -Xmx512m -Xms64m -jar mms.jar'
       cd $MAS_HOME/mms/
       java -Xmx512m -Xms64m -jar mms.jar  >/dev/null 2>&1 &
     else
       echo "mms.jar not exist,start failed"
     fi
   fi
}

#彩信停止
MmsStop()
{
  echo "begin to close mms"
   ps -fu `whoami` | grep -E "mms.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}

#------------------------------------------SPS-------------------------------------------------
#sps启动
SpsStart(){
   if ps -fu `whoami`|grep -E sps.jar|grep -E java >/dev/null 2>&1 ;then
      echo "sps exist"
   else
     if [ -f $MAS_HOME/sps/sps.jar ] 
     then
       echo 'begin to start sps: java -jar sps.jar'
       cd $MAS_HOME/sps/
       java -jar sps.jar  >/dev/null 2>&1 &
     else
       echo "sps.jar not exist,start failed"
     fi
   fi
}

#sps停止
SpsStop()
{
   echo "begin to close sps"
   ps -fu `whoami` | grep -E "sps.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}



#------------------------------------------mon-------------------------------------------------
#sps启动
MonitorStart(){
   if ps -fu `whoami`|grep -E mon.jar|grep -E java >/dev/null 2>&1 ;then
      echo "mon exist"
   else
     if [ -f $MAS_HOME/mon/mon.jar ] 
     then
       echo 'begin to start mon: java -jar mon.jar'
       cd $MAS_HOME/mon/
       java -jar mon.jar  >/dev/null 2>&1 &
     else
       echo "mon.jar not exist,start failed"
     fi
   fi
}

#sps停止
MonitorStop()
{
   echo "begin to close mon"
   ps -fu `whoami` | grep -E "mon.jar" | grep -E "java" | awk '{print $2}' | xargs kill -9 2>/dev/null
}


#------------------------------------------END------------------------------------------

#mas停止
MasStop(){
  if [ "x$1" = x ] ;then
    command="all"
  else
    command=$1
  fi
  
  case $command in
    mtm)
      MtmStop
      ;;
    masagent)
      MasagentStop
      ;;
    was)
      WasStop
      ;;
    sms)
      SmsStop
      ;;
    eup)
      EupStop
      ;;        
    mms)
      MmsStop
      ;;
    sps)
      SpsStop
      ;;
#    mon)
#      MonitorStop
#      ;;
    all)
#      MonitorStop
      MasagentStop
      WasStop
      SmsStop
#      EupStop
      MmsStop
      SpsStop
      MtmStop
      ;;
    *)
      CommondError
      ;;
  esac
}

#mas重启
MasRestart(){

  if [ "x$1" = x ] ;then
    command="all"
  else
    command=$1
  fi
  
  case $command in
    mtm)
      MtmStop
      sleep 3
      MtmStart
      ;;
    masagent)
      MasagentStop
      sleep 3
      MasagentStart
      ;;
    was)
      WasStop
      sleep 3
      WasStart
      ;;
    sms)
      SmsStop
      sleep 3
      SmsStart
      ;;
#    eup)
#      EupStop
#      sleep 3
#      EupStart
#      ;;        
    mms)
      MmsStop
      sleep 3
      MmsStart
      ;;
    sps)
      SpsStop
      sleep 3
      SpsStart
      ;;
#    mon)
#      MonitorStop
#      sleep 3
#      MonitorStart
#      ;;
    all)
#      MonitorStop
      MasagentStop
      WasStop
      SmsStop
#      EupStop
      MmsStop
      SpsStop
      MtmStop
      
      sleep 5
      
#      MtmStart      
#      MasagentStart
      WasStart
      SmsStart
#      EupStart
#      MmsStart
#      SpsStart     
#      MonitorStart
      ;;
    *)
      CommondError
      ;;
  esac
  
  
}

#mas启动
MasStart(){

  if [ "x$1" = x ] ;then
    command="all"
  else
    command=$1
  fi

case $command in
    mtm)
      MtmStart
      ;;
    masagent)
      MasagentStart
      ;;
    was)
      WasStart
      ;;
    sms)
      SmsStart
      ;;
    eup)
      EupStart
      ;;        
    mms)
      MmsStart
      ;;
    sps)
      SpsStart
      ;;
#    mon)
#      MonitorStart
#      ;;
    all)
#      MtmStart      
#      MasagentStart
      WasStart
      SmsStart
#      EupStart
#      MmsStart
#      SpsStart     
      #MonitorStart
      ;;
    *)
      CommondError
      ;;
esac
}

#初始化，检查参数
Init(){


if [ "x$MAS_HOME" = "x" ];then
    echo "MAS_HOME环境变量未设置"
    exit 1
fi

if [ "x$JAVA_HOME" = "x" ]; then
    echo "JAVA_HOME环境变量未设置"
    exit 2
fi

if [ -x $JAVA_HOME/bin/java ]; then
    printf ""
else
    echo "错误的JAVAHOME环境变量设置。$JAVA_HOME/bin/java 程序不存在。"
    echo "请重新指定JDK安装路径。"
    exit 3
fi
}



Init

if [ "x$3" = x ] ;then
  printf ""
else
  CommondError
  exit 9
  
fi

case $1 in 
   version) 
   MasVersion
   ;;
   stop)
   MasStop $2
   ;;
   start)
   MasStart $2
   ;;
   restart)
   MasRestart $2
   ;;
   status)
   MasStatus
   ;;
   help)
   Mashelp 
   ;;
   *)
   Mashelp
   ;;
esac


