rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/huawei/1
rm -r /data33/aijs/center/log/daystat/wj/voice/huawei
rm -r /data33/aijs/center/data/back/daystat/output/wj/voice/huawei
rm -r /data33/aijs/center/error/daystat/output/wj/voice/huawei
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/huawei
rm -r /data33/aijs/center/data/daystat/skip/wj/voice/huawei
rm -r /data33/aijs/center/error/dataloader/daystat/wj/voice/huawei
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/huawei/2
rm -r /data33/aijs/center/log/dataloader/daystat/wj/voice/huawei
rm -r /data33/aijs/center/data/dataloader/stat/wj/voice/huawei
rm -r /data33/aijs/center/error/dataloader/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/output/wj/voice/nokia
rm -r /data33/aijs/center/log/dataloader/wj/voice/nokia
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/nokia
rm -r /data33/aijs/center/error/dataloader/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/output/wj/voice/alcatel
rm -r /data33/aijs/center/log/dataloader/wj/voice/alcatel
rm -r /data33/aijs/center/error/dataloader/daystat/wj/voice/nokia
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/nokia/2
rm -r /data33/aijs/center/log/dataloader/daystat/wj/voice/nokia
rm -r /data33/aijs/center/data/dataloader/stat/wj/voice/nokia
rm -r /data33/aijs/center/error/dataloader/daystat/wj/voice/alcatel
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/alcatel/2
rm -r /data33/aijs/center/log/dataloader/daystat/wj/voice/alcatel
rm -r /data33/aijs/center/data/dataloader/stat/wj/voice/alcatel
rm -r /data33/aijs/center/error/dataldrgen/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/output/wj/voice/nokia
rm -r /data33/aijs/center/log/dataldrgen/wj/voice/nokia
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/nokia
rm -r /data33/aijs/center/error/dataldrgen/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/output/wj/voice/alcatel
rm -r /data33/aijs/center/log/dataldrgen/wj/voice/alcatel
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/alcatel
rm -r /data32/home/aijs/center/config/acquire/wj/voice/nokia
rm -r /data33/aijs/center/log/acquire/wj/voice/nokia
rm -r /data33/aijs/center/data/acquire/output/wj/voice/nokia
rm -r /wjdata/lihui/center/back/data_wj
rm -r /data33/aijs/center/temp/acquire/wj/voice/nokia
rm -r /data32/home/aijs/center/config/acquire/wj/voice/alcatel
rm -r /data33/aijs/center/log/acquire/wj/voice/alcatel
rm -r /data33/aijs/center/data/acquire/output/wj/voice/alcatel
rm -r /wjdata/lihui/center/back/data_wj
rm -r /data33/aijs/center/temp/acquire/wj/voice/alcatel
rm -r /data33/aijs/center/log/settle/wj/voice/nokia
rm -r /data33/aijs/center/back/settle/wj/voice/nokia
rm -r /data33/aijs/center/error/settle/wj/voice/nokia
rm -r /data33/aijs/center/data/format/output/wj/voice/nokia
rm -r /data33/aijs/center/data/settle/output/wj/voice/nokia
rm -r /data33/aijs/center/log/settle/wj/voice/alcatel
rm -r /data33/aijs/center/back/settle/wj/voice/alcatel
rm -r /data33/aijs/center/error/settle/wj/voice/alcatel
rm -r /data33/aijs/center/data/format/output/wj/voice/alcatel
rm -r /data33/aijs/center/data/settle/output/wj/voice/alcatel
rm -r /data33/aijs/center/log/stat/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/output/wj/voice/nokia
rm -r /data33/aijs/center/error/stat/wj/voice/nokia
rm -r /data33/aijs/center/data/settle/output/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/skip/wj/voice/nokia
rm -r /data33/aijs/center/log/stat/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/output/wj/voice/alcatel
rm -r /data33/aijs/center/error/stat/wj/voice/alcatel
rm -r /data33/aijs/center/data/settle/output/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/skip/wj/voice/alcatel
rm -r /data33/aijs/center/log/settle/wj/voice/huawei
rm -r /data33/aijs/center/back/settle/wj/voice/huawei
rm -r /data33/aijs/center/error/settle/wj/voice/huawei
rm -r /data33/aijs/center/data/format/output/wj/voice/huawei
rm -r /data33/aijs/center/data/settle/output/wj/voice/huawei
rm -r /data33/aijs/center/error/dataldrgen/wj/voice/huawei
rm -r /data33/aijs/center/data/stat/output/wj/voice/huawei
rm -r /data33/aijs/center/log/dataldrgen/wj/voice/huawei
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/huawei
rm -r /data33/aijs/center/log/daystat/wj/voice/alcatel
rm -r /data33/aijs/center/data/back/daystat/output/wj/voice/alcatel
rm -r /data33/aijs/center/error/daystat/output/wj/voice/alcatel
rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/alcatel/1
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/alcatel
rm -r /data33/aijs/center/data/daystat/skip/wj/voice/alcatel
rm -r /data33/aijs/center/log/daystat/wj/voice/nokia
rm -r /data33/aijs/center/data/back/daystat/output/wj/voice/nokia
rm -r /data33/aijs/center/error/daystat/output/wj/voice/nokia
rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/nokia/1
rm -r /data33/aijs/center/data/daystat/statoutput/wj/voice/nokia
rm -r /data33/aijs/center/data/daystat/skip/wj/voice/nokia
rm -r /data33/aijs/center/back/dataloader/cdr/wj/voice/huawei
rm -r /data33/aijs/center/temp/dataloader/wj/voice/huawei
rm -r /data33/aijs/center/back/dataloader/cdr/wj/voice/nokia
rm -r /data33/aijs/center/temp/dataloader/wj/voice/nokia
rm -r /data33/aijs/center/data/format/output/wj/voice/alcatel
rm -r /data33/aijs/center/data/acquire/output/wj/voice/alcatel
rm -r /data33/aijs/center/log/format/wj/voice/alcatel
rm -r /data33/aijs/center/temp/format/wj/voice/alcatel
rm -r /data32/home/aijs/center/dup/format/wj/voice/alcatel
rm -r /data33/aijs/center/error/format/wj/voice/alcatel
rm -r /data32/home/aijs/center/dup/format/wj/voice/nokia
rm -r /data33/aijs/center/error/format/wj/voice/nokia
rm -r /data33/aijs/center/data/format/output/wj/voice/nokia
rm -r /data33/aijs/center/data/acquire/output/wj/voice/nokia
rm -r /data33/aijs/center/log/format/wj/voice/nokia
rm -r /data33/aijs/center/temp/format/wj/voice/nokia
rm -r /data33/aijs/center/log/stat/wj/voice/huawei
rm -r /data33/aijs/center/data/stat/output/wj/voice/huawei
rm -r /data33/aijs/center/error/stat/wj/voice/huawei
rm -r /data33/aijs/center/data/settle/output/wj/voice/huawei
rm -r /data33/aijs/center/data/stat/statoutput/wj/voice/huawei
rm -r /data33/aijs/center/data/stat/skip/wj/voice/huawei
rm -r /data33/aijs/center/error/dataloader/wj/voice/huawei
rm -r /data33/aijs/center/data/stat/output/wj/voice/huawei
rm -r /data33/aijs/center/log/dataloader/wj/voice/huawei
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/huawei
rm -r /data32/home/aijs/center/dup/format/wj/voice/huawei
rm -r /data33/aijs/center/error/format/wj/voice/huawei
rm -r /data33/aijs/center/data/format/output/wj/voice/huawei
rm -r /data33/aijs/center/data/acquire/output/wj/voice/huawei
rm -r /data33/aijs/center/log/format/wj/voice/huawei
rm -r /data33/aijs/center/temp/format/wj/voice/huawei
rm -r /data33/aijs/center/temp/dataloader/stat/wj/voice/nokia
rm -r /data32/home/aijs/center/config/acquire/wj/voice/huawei
rm -r /data33/aijs/center/log/acquire/wj/voice/huawei
rm -r /data33/aijs/center/data/acquire/output/wj/voice/huawei
rm -r /wjdata/lihui/center/back/data_wj
rm -r /data33/aijs/center/temp/acquire/wj/voice/huawei
rm -r /data33/aijs/center/back/dataloader/stat/wj/voice/alcatel
rm -r /data33/aijs/center/temp/dataloader/stat/wj/voice/alcatel
rm -r /data33/aijs/center/back/dataloader/cdr/wj/voice/alcatel
rm -r /data33/aijs/center/data/dataloader/output/wj/voice/alcatel
rm -r /data33/aijs/center/temp/dataloader/wj/voice/alcatel
rm -r /data33/aijs/center/back/dataloader/stat/wj/voice/huawei
rm -r /data33/aijs/center/temp/dataloader/stat/wj/voice/huawei
rm -r /data33/aijs/center/back/dataloader/stat/wj/voice/nokia
rm -r /data33/aijs/center/error/dataloader/err/huawei
rm -r /data33/aijs/center/error/settle/wj/voice/huawei
rm -r /data33/aijs/center/log/dataloader/err/wj/voice/huawei
rm -r /data33/aijs/center/back/dataloader/err/wj/voice/huawei
rm -r /data33/aijs/center/error/dataloader/err/alcatel
rm -r /data33/aijs/center/error/settle/wj/voice/alcatel
rm -r /data33/aijs/center/log/dataloader/err/wj/voice/alcatel
rm -r /data33/aijs/center/back/dataloader/err/wj/voice/alcatel
rm -r /data33/aijs/center/error/dataloader/err/nokia
rm -r /data33/aijs/center/error/settle/wj/voice/nokia
rm -r /data33/aijs/center/log/dataloader/err/wj/voice/nokia
rm -r /data33/aijs/center/back/dataloader/err/wj/voice/nokia
