du -sk /data33/aijs/center/error/settle/wj/voice/alcatel
du -sk /data33/aijs/center/error/settle/wj/voice/nokia
du -sk /data33/aijs/center/error/format/wj/voice/alcatel
du -sk /data33/aijs/center/error/format/wj/voice/nokia
du -sk /data33/aijs/center/error/settle/wj/voice/huawei
du -sk /data33/aijs/center/error/format/wj/voice/huawei
du -sk /data33/aijs/center/error/settle/wj/voice/alcatel
du -sk /data33/aijs/center/error/settle/wj/voice/huawei
du -sk /data33/aijs/center/error/dataloader/wj/voice/nokia
du -sk /data33/aijs/center/error/dataloader/wj/voice/alcatel
du -sk /data33/aijs/center/error/daystat/wj/voice/huawei
du -sk /data33/aijs/center/error/daystat/wj/voice/nokia
du -sk /data33/aijs/center/error/daystat/wj/voice/alcatel
du -sk /data33/aijs/center/error/daydataloader/wj/voice/alcatel
du -sk /data33/aijs/center/error/stat/wj/voice/alcatel
du -sk /data33/aijs/center/error/dataloader/wj/voice/huawei
du -sk /data33/aijs/center/error/stat/wj/voice/nokia
du -sk /data33/aijs/center/error/daydataloader/wj/voice/huawei
du -sk /data33/aijs/center/error/daydataloader/wj/voice/nokia
du -sk /data33/aijs/center/error/stat/wj/voice/huawei
