mkdir -p /data3/center/back/dataloader/stat/roam/sp/nmpp
mkdir -p /data3/center/error/daydataloader/roam/sp/nmpp
mkdir -p /data3/center/data/daystat/output/roam/sp/nmpp
mkdir -p /data3/center/log/daydataloader/roam/sp/nmpp
mkdir -p /data3/center/data/daydataloader/output/roam/sp/nmpp
mkdir -p /data3/center/temp/daydataloader/roam/sp/nmpp
mkdir -p /data3/center/back/dataloader/cdr/roam/sp/nmpp
mkdir -p /data3/center/error/dataloader/roam/sp/nmpp
mkdir -p /data3/center/data/dataloader/output/roam/sp/nmpp
mkdir -p /data3/center/log/dataloader/roam/sp/nmpp
mkdir -p /data3/center/data/dataloader/cdr/roam/sp/nmpp
mkdir -p /data3/center/temp/dataloader/cdr/roam/sp/nmpp
mkdir -p /data3/center/back/stat/output/roam/sp/nmpp
mkdir -p /data3/center/error/stat/roam/sp/nmpp
mkdir -p /data3/center/data/settle/output/roam/sp/nmpp
mkdir -p /data3/center/data/stat/statoutput/roam/sp/nmpp
mkdir -p /data3/center/data/stat/skip/roam/sp/nmpp
mkdir -p /data3/center/back/settle/roam/sp/nmpp
mkdir -p /data3/center/error/settle/roam/sp/nmpp
mkdir -p /data3/center/data/format/output/roam/sp/nmpp
mkdir -p /data3/center/data/settle/output/roam/sp/nmpp
mkdir -p /data3/center/dup/format/roam/sp/nmpp
mkdir -p /data3/center/dup/format/roam/sp/nmpp
mkdir -p /data3/center/error/format/roam/sp/nmpp
mkdir -p /data3/center/data/format/output/roam/sp/nmpp
mkdir -p /data3/center/data/acquire/output/roam/sp/nmpp
mkdir -p /data3/center/log/format/roam/sp/nmpp
mkdir -p /data3/center/temp/format/roam/sp/nmpp
