# select 'echo "'||b.module_id||b.module_name, b.module_code, 
# ':\t\c"; l ' || a.param_value || '|wc -w' "MODULE_INFO FILE_NUMBER"
# from sys_module_param_detail a, sys_module b
# where a.param_code = 'inputPath'
# and a.module_id=b.module_id  AND b.module_id not in ('100411', '180002', '120711', '130711', '160712')
# and module_name not like '加载错单%' and module_name not like '%临时%'
# order by a.module_id, a.param_code;
echo "110011	预处理_SP_GSM			prep_sp_gsm				:\t\c"; l /data3/center/data/acquire/output/sp/billing/gsm|wc -w                         
echo "110021	预处理_SP_ISMG          prep_sp_ismg            :\t\c"; l /data3/center/data/acquire/output/sp/billing/ismg|wc -w           
echo "110022	预处理_SP_SMS           prep_sp_sms             :\t\c"; l /data3/center/data/acquire/output/sp/billing/sms|wc -w            
echo "110031	预处理_SP_WAP           prep_sp_wap             :\t\c"; l /data3/center/data/acquire/output/sp/billing/wap|wc -w            
echo "110041	预处理_SP_MMS           prep_sp_mms             :\t\c"; l /data3/center/data/acquire/output/sp/billing/mms|wc -w            
echo "110042	预处理_SP_KJAVA         prep_sp_kjava           :\t\c"; l /data3/center/data/acquire/output/sp/billing/kjava|wc -w          
echo "110051	预处理_营业帐单         prep_user_bill          :\t\c"; l /data3/center/data/acquire/output/sp/bill|wc -w                   
echo "110061	预处理_梦网稽核         prep_mcas_sms           :\t\c"; l /data3/center/data/acquire/output/sp/dream|wc -w                  
echo "110411	预处理_网间_短信        prep_sms                :\t\c"; l /data2/wj/center/data/acquire/output/wj/sms|wc -w                 
echo "110451	预处理_网间_华为        prep_hw                 :\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/huawei|wc -w        
echo "110452	预处理_网间_诺基亚      prep_nokia              :\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/nokia|wc -w         
echo "110453	预处理_网间_阿尔卡特    prep_alcatel            :\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/alcatel|wc -w       
echo "110454	预处理_网间_华为_temp   prep_hw2                :\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/huawei/temp|wc -w   
echo "110611	预处理_省际_GPRS        prep_roam_gprs          :\t\c"; l /data3/center/data/acquire/output/roam/gprs|wc -w                 
echo "110612	预处理_省际_CNG         prep_roam_cng           :\t\c"; l /data3/center/data/acquire/output/roam/cng|wc -w                  
echo "110621	预处理_省际_KJAVA       prep_roam_kjava         :\t\c"; l /data3/center/data/acquire/output/roam/sp/kjava|wc -w             
echo "110631	预处理_省际_MMS         prep_roam_mms           :\t\c"; l /data3/center/data/acquire/output/roam/sp/mms|wc -w               
echo "110641	预处理_省际_WAP         prep_roam_wap           :\t\c"; l /data3/center/data/acquire/output/roam/sp/wap|wc -w               
echo "110651	预处理_省际_短信        prep_roam_sms           :\t\c"; l /data3/center/data/acquire/output/roam/sp/sms|wc -w               
echo "110661	预处理_省际_小额支付    prep_roam_nmpp          :\t\c"; l /data3/center/data/acquire/output/roam/sp/nmpp|wc -w              
echo "110671	预处理_省际_STM         prep_roam_stm           :\t\c"; l /data3/center/data/acquire/output/roam/sp/stm|wc -w               
echo "110681	预处理_省际_CRG         prep_roam_crg           :\t\c"; l /data3/center/data/acquire/output/roam/sp/crg|wc -w               
echo "110691	预处理_省际_MP          prep_roam_mp            :\t\c"; l /data3/center/data/acquire/output/roam/sp/mp|wc -w                
echo "110701	预处理_省际_VC          prep_roam_vc            :\t\c"; l /data3/center/data/acquire/output/roam/refill/vc|wc -w            
echo "110711	预处理_省际_SM          prep_roam_sm            :\t\c"; l /data3/center/data/acquire/output/roam/sp/sm|wc -w                
echo "110751	预处理_省际_IPC         prep_roam_ipcard        :\t\c"; l /data3/center/data/acquire/output/roam/voice/ipcard|wc -w         
echo "110761	预处理_省际_PPS         prep_roam_pps           :\t\c"; l /data3/center/data/acquire/output/roam/voice/pps|wc -w            
echo "110771	预处理_省际_音信        prep_roam_rq            :\t\c"; l /data3/center/data/acquire/output/roam/voice/rq|wc -w             
echo "110781	预处理_省际_换机        prep_roam_korea         :\t\c"; l /data3/center/data/acquire/output/roam/voice/korea|wc -w          
echo "110791	预处理_省际_语音        prep_roam_voice         :\t\c"; l /data3/center/data/acquire/output/roam/voice/voice|wc -w          
echo "110792	预处理_省际_语音2       prep_roam_voice2        :\t\c"; l /data3/center/data/acquire/output/roam/voice/voice/2|wc -w        
echo "110793	预处理_省际_语音3       prep_roam_voice3        :\t\c"; l /data3/center/data/acquire/output/roam/voice/voice/3|wc -w        
echo "110801	预处理_省际_汇总        prep_roam_sum           :\t\c"; l /data3/center/data/acquire/output/roam/sum|wc -w                  
echo "110802	预处理_省际_汇总2       prep_roam_sum2          :\t\c"; l /data3/center/data/acquire/output/roam/sum2|wc -w                 
echo "110803	预处理_省际_梦网短信    prep_roam_ismg          :\t\c"; l /data3/center/data/acquire/output/roam/sp/ismg|wc -w              
echo "120011	分析_SP_GSM             settle_sp_gsm           :\t\c"; l /data3/center/data/format/output/sp/billing/gsm|wc -w             
echo "120021	分析_SP_ISMG1           settle_sp_ismg1         :\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w            
echo "120022	分析_SP_ISMG2           settle_sp_ismg2         :\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w            
echo "120023	分析_SP_ISMG3           settle_sp_ismg3         :\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w            
echo "120024	分析_SP_ISMG4           settle_sp_ismg4         :\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w            
echo "120031	分析_SP_MMS             settle_sp_mms           :\t\c"; l /data3/center/data/format/output/sp/billing/mms|wc -w             
echo "120032	分析_SP_MMS2            settle_sp_mms2          :\t\c"; l /data3/center/data/format/output/sp/billing/mms2|wc -w            
echo "120033	分析_SP_MMS3            settle_sp_mms3          :\t\c"; l /data3/center/data/format/output/sp/billing/mms3|wc -w            
echo "120041	分析_SP_WAP             settle_sp_wap           :\t\c"; l /data3/center/data/format/output/sp/billing/wap|wc -w             
echo "120042	分析_SP_KJAVA           settle_sp_kjava         :\t\c"; l /data3/center/data/format/output/sp/billing/kjava|wc -w           
echo "120051	分析_营业帐单           settle_user_bill        :\t\c"; l /data3/center/data/format/output/sp/bill|wc -w                    
echo "120061	分析_梦网稽核           settle_mcas_sms         :\t\c"; l /data3/center/data/format/output/sp/dream|wc -w                   
echo "120411	分析_网间_短信          settle_sms              :\t\c"; l /data2/wj/center/data/format/output/wj/sms|wc -w                  
echo "120451	分析_网间_华为          settle_hw               :\t\c"; l /data2/wj/center/data/format/output/wj/voice/huawei|wc -w         
echo "120452	分析_网间_诺基亚        settle_nokia            :\t\c"; l /data2/wj/center/data/format/output/wj/voice/nokia|wc -w          
echo "120453	分析_网间_阿尔卡特      settle_alcatel          :\t\c"; l /data2/wj/center/data/format/output/wj/voice/alcatel|wc -w        
echo "120454	分析_网间_阿尔卡特2     settle_alcatel2         :\t\c"; l /data2/wj/center/data/format/output/wj/voice/alcatel|wc -w        
echo "120455	分析_网间_华为2         settle_hw2              :\t\c"; l /data2/wj/center/data/format/output/wj/voice/huawei|wc -w         
echo "120611	分析_省际_GPRS          settle_roam_gprs        :\t\c"; l /data3/center/data/format/output/roam/gprs|wc -w                  
echo "120621	分析_省际_KJAVA         settle_roam_kjava       :\t\c"; l /data3/center/data/format/output/roam/sp/kjava|wc -w              
echo "120631	分析_省际_MMS           settle_roam_mms         :\t\c"; l /data3/center/data/format/output/roam/sp/mms|wc -w                
echo "120641	分析_省际_WAP           settle_roam_wap         :\t\c"; l /data3/center/data/format/output/roam/sp/wap|wc -w                
echo "120651	分析_省际_短信          settle_roam_sms         :\t\c"; l /data3/center/data/format/output/roam/sp/sms|wc -w                
echo "120661	分析_省际_小额支付      settle_roam_nmpp        :\t\c"; l /data3/center/data/format/output/roam/sp/nmpp|wc -w               
echo "120671	分析_省际_STM           settle_roam_stm         :\t\c"; l /data3/center/data/format/output/roam/sp/stm|wc -w                
echo "120681	分析_省际_CRG           settle_roam_crg         :\t\c"; l /data3/center/data/format/output/roam/sp/crg|wc -w                
echo "120691	分析_省际_MP            settle_roam_mp          :\t\c"; l /data3/center/data/format/output/roam/sp/mp|wc -w                 
echo "120701	分析_省际_VC            settle_roam_vc          :\t\c"; l /data3/center/data/format/output/roam/refill/vc|wc -w             
echo "120751	分析_省际_IPC           settle_roam_ipcard      :\t\c"; l /data3/center/data/format/output/roam/voice/ipcard|wc -w          
echo "120761	分析_省际_PPS           settle_roam_pps         :\t\c"; l /data3/center/data/format/output/roam/voice/pps|wc -w             
echo "120771	分析_省际_音信          settle_roam_rq          :\t\c"; l /data3/center/data/format/output/roam/voice/rq|wc -w              
echo "120781	分析_省际_换机          settle_roam_korea       :\t\c"; l /data3/center/data/format/output/roam/voice/korea|wc -w           
echo "120791	分析_省际_语音          settle_roam_voice       :\t\c"; l /data3/center/data/format/output/roam/voice/voice|wc -w           
echo "120792	分析_省际_梦网短信      settle_roam_ismg        :\t\c"; l /data3/center/data/format/output/roam/sp/ismg|wc -w               
echo "120793	分析_省际_语音3         settle_roam_voice3      :\t\c"; l /data3/center/data/format/output/roam/voice/voice/3|wc -w         
echo "120794	分析_省际_语音2         settle_roam_voice2      :\t\c"; l /data3/center/data/format/output/roam/voice/voice/2|wc -w         
echo "130011	汇总_SP_GSM             stat_sp_gsm             :\t\c"; l /data3/center/data/settle/output/sp/billing/gsm|wc -w             
echo "130021	汇总_SP_ISMG1           stat_sp_ismg1           :\t\c"; l /data3/center/data/settle/output/sp/billing/ismg|wc -w            
echo "130023	汇总_SP_ISMG2           stat_sp_ismg2           :\t\c"; l /data3/center/data/settle/output/sp/billing/ismg|wc -w            
echo "130031	汇总_SP_MMS             stat_sp_mms             :\t\c"; l /data3/center/data/settle/output/sp/billing/mms|wc -w             
echo "130041	汇总_SP_WAP             stat_sp_wap             :\t\c"; l /data3/center/data/settle/output/sp/billing/wap|wc -w             
echo "130042	汇总_SP_KJAVA           stat_sp_kjava           :\t\c"; l /data3/center/data/settle/output/sp/billing/kjava|wc -w           
echo "130051	汇总_营业帐单           stat_user_bill          :\t\c"; l /data3/center/data/settle/output/sp/bill|wc -w                    
echo "130411	汇总_网间_短信          stat_sms                :\t\c"; l /data2/wj/center/data/settle/output/wj/sms|wc -w                  
echo "130451	汇总_网间_华为          stat_hw                 :\t\c"; l /data2/wj/center/data/settle/output/wj/voice/huawei|wc -w         
echo "130453	汇总_网间_诺基亚        stat_nokia              :\t\c"; l /data2/wj/center/data/settle/output/wj/voice/nokia|wc -w          
echo "130455	汇总_网间_阿尔卡特      stat_alcatel            :\t\c"; l /data2/wj/center/data/settle/output/wj/voice/alcatel|wc -w        
echo "130611	汇总_省际_GPRS          stat_roam_gprs          :\t\c"; l /data3/center/data/settle/output/roam/gprs|wc -w                  
echo "130621	汇总_省际_KJAVA         stat_roam_kjava         :\t\c"; l /data3/center/data/settle/output/roam/sp/kjava|wc -w              
echo "130631	汇总_省际_MMS           stat_roam_mms           :\t\c"; l /data3/center/data/settle/output/roam/sp/mms|wc -w                
echo "130641	汇总_省际_WAP           stat_roam_wap           :\t\c"; l /data3/center/data/settle/output/roam/sp/wap|wc -w                
echo "130651	汇总_省际_短信          stat_roam_sms           :\t\c"; l /data3/center/data/settle/output/roam/sp/sms|wc -w                
echo "130661	汇总_省际_小额支付      stat_roam_nmpp          :\t\c"; l /data3/center/data/settle/output/roam/sp/nmpp|wc -w               
echo "130671	汇总_省际_STM           stat_roam_stm           :\t\c"; l /data3/center/data/settle/output/roam/sp/stm|wc -w                
echo "130681	汇总_省际_CRG           stat_roam_crg           :\t\c"; l /data3/center/data/settle/output/roam/sp/crg|wc -w                
echo "130691	汇总_省际_MP            stat_roam_mp            :\t\c"; l /data3/center/data/settle/output/roam/sp/mp|wc -w                 
echo "130701	汇总_省际_VC充值        stat_roam_vc            :\t\c"; l /data3/center/data/settle/output/roam/refill/vc|wc -w             
echo "130751	汇总_省际_IP记帐卡      stat_roam_ipcard        :\t\c"; l /data3/center/data/settle/output/roam/voice/ipcard|wc -w          
echo "130761	汇总_省际_PPS           stat_roam_pps           :\t\c"; l /data3/center/data/settle/output/roam/voice/pps|wc -w             
echo "130771	汇总_省际_音信          stat_roam_rq            :\t\c"; l /data3/center/data/settle/output/roam/voice/rq|wc -w              
echo "130781	汇总_省际_换机          stat_roam_korea         :\t\c"; l /data3/center/data/settle/output/roam/voice/korea|wc -w           
echo "130791	汇总_省际_语音          stat_roam_voice         :\t\c"; l /data3/center/data/settle/output/roam/voice/voice|wc -w           
echo "130792	汇总_省际_梦网短信      stat_roam_ismg          :\t\c"; l /data3/center/data/settle/output/roam/sp/ismg|wc -w               
echo "140012	日汇总_SP_GSM           daystat_sp_gsm          :\t\c"; l /data3/center/data/stat/statoutput/sp/billing/gsm/5|wc -w         
echo "140022	日汇总_SP_ISMG          daystat_sp_ismg         :\t\c"; l /data3/center/data/stat/statoutput/sp/billing/ismg/7|wc -w        
echo "140032	日汇总_SP_MMS           daystat_sp_mms          :\t\c"; l /data3/center/data/stat/statoutput/sp/billing/mms/9|wc -w         
echo "140042	日汇总_SP_WAP           daystat_sp_wap          :\t\c"; l /data3/center/data/stat/statoutput/sp/billing/wap/11|wc -w        
echo "140072	日汇总_SP_KJAVA         daystat_sp_kjava        :\t\c"; l /data3/center/data/stat/statoutput/sp/billing/kjava/15|wc -w      
echo "140412	日汇总_网间_短信        daystat_sms             :\t\c"; l /data2/wj/center/data/stat/statoutput/wj/sms/3|wc -w              
echo "140452	日汇总_网间_华为        daystat_hw              :\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/huawei/1|wc -w     
echo "140454	日汇总_网间_诺基亚      daystat_nokia           :\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/nokia/1|wc -w      
echo "140456	日汇总_网间_阿尔卡特    daystat_alcatel         :\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/alcatel/1|wc -w    
echo "150011	加载清单_SP_GSM         ldrmain_sp_gsm          :\t\c"; l /data3/center/back/stat/output/sp/billing/gsm|wc -w               
echo "150021	加载清单_SP_ISMG        ldrmain_sp_ismg         :\t\c"; l /data3/center/back/stat/output/sp/billing/ismg|wc -w              
echo "150031	加载清单_SP_MMS         ldrmain_sp_mms          :\t\c"; l /data3/center/back/stat/output/sp/billing/mms|wc -w               
echo "150041	加载清单_SP_WAP         ldrmain_sp_wap          :\t\c"; l /data3/center/back/stat/output/sp/billing/wap|wc -w               
echo "150042	加载清单_SP_KJAVA       ldrmain_sp_kjava        :\t\c"; l /data3/center/data/stat/output/sp/billing/kjava|wc -w             
echo "150051	加载清单_营业帐单       ldrmain_user_bill       :\t\c"; l /data3/center/back/stat/output/sp/bill|wc -w                      
echo "150411	加载清单_网间_短信      ldrmain_sms_data        :\t\c"; l /data2/wj/center/back/stat/output/wj/sms|wc -w                    
echo "150451	加载清单_网间_华为      ldr_huawei              :\t\c"; l /data2/wj/center/back/stat/output/wj/voice/huawei|wc -w           
echo "150453	加载清单_网间_诺基亚    ldr_nokia               :\t\c"; l /data2/wj/center/back/stat/output/wj/voice/nokia|wc -w            
echo "150455	加载清单_网间_阿尔卡特  ldr_alcatel             :\t\c"; l /data2/wj/center/back/stat/output/wj/voice/alcatel|wc -w          
echo "150456	加载清单_网间_阿尔卡特2 ldr_alcatel2            :\t\c"; l /data2/wj/center/back/stat/output/wj/voice/alcatel|wc -w          
echo "150611	加载清单_省际_GPRS      ldrmain_roam_gprs       :\t\c"; l /data3/center/back/stat/output/roam/gprs|wc -w                    
echo "150621	加载清单_省际_KJAVA     ldrmain_roam_kjava      :\t\c"; l /data3/center/back/stat/output/roam/sp/kjava|wc -w                
echo "150631	加载清单_省际_MMS       ldrmain_roam_mms        :\t\c"; l /data3/center/back/stat/output/roam/sp/mms|wc -w                  
echo "150641	加载清单_省际_WAP       ldrmain_roam_wap        :\t\c"; l /data3/center/back/stat/output/roam/sp/wap|wc -w                  
echo "150651	加载清单_省际_短信      ldrmain_roam_sms        :\t\c"; l /data3/center/back/stat/output/roam/sp/sms|wc -w                  
echo "150661	加载清单_省际_小额支付  ldrmain_roam_nmpp       :\t\c"; l /data3/center/data/dataloader/output/roam/sp/nmpp|wc -w           
echo "150671	加载清单_省际_STM       ldrmain_roam_stm        :\t\c"; l /data3/center/back/stat/output/roam/sp/stm|wc -w                  
echo "150681	加载清单_省际_CRG       ldrmain_roam_crg        :\t\c"; l /data3/center/back/stat/output/roam/sp/crg|wc -w                  
echo "150691	加载清单_省际_MP        ldrmain_roam_mp         :\t\c"; l /data3/center/back/stat/output/roam/sp/mp|wc -w                   
echo "150701	加载清单_省际_VC        ldrmain_roam_vc         :\t\c"; l /data3/center/back/stat/output/roam/refill/vc|wc -w               
echo "150711	加载清单_省际_VIP       ldrmain_roam_vip        :\t\c"; l /data3/center/data/stat/output/roam/refill/vip|wc -w              
echo "150751	加载清单_省际_IPC       ldrmain_roam_ipcard     :\t\c"; l /data3/center/data/dataloader/output/roam/voice/ipcard|wc -w      
echo "150761	加载清单_省际_PPS       ldrmain_roam_pps        :\t\c"; l /data3/center/back/stat/output/roam/voice/pps|wc -w               
echo "150771	加载清单_省际_音信      ldrmain_roam_rq         :\t\c"; l /data3/center/back/stat/output/roam/voice/rq|wc -w                
echo "150781	加载清单_省际_换机      ldrmain_roam_korea      :\t\c"; l /data3/center/data/stat/output/roam/voice/korea|wc -w             
echo "150791	加载清单_省际_语音      ldrmain_roam_voice      :\t\c"; l /data3/center/back/stat/output/roam/voice/voice|wc -w             
echo "150794	加载清单_省际_梦网短信  ldrmain_roam_ismg       :\t\c"; l /data3/center/back/stat/output/roam/sp/ismg|wc -w                 
echo "160012	加载帐单_SP_ISMG        ldrmain_sp_ismg_stat    :\t\c"; l /data3/center/data/daystat/output/sp/billing/ismg/8|wc -w         
echo "160022	加载帐单_SP_MMS         ldrmain_sp_mms_stat     :\t\c"; l /data3/center/data/daystat/output/sp/billing/mms/10|wc -w         
echo "160032	加载帐单_SP_WAP         ldrmain_sp_wap_stat     :\t\c"; l /data3/center/data/daystat/output/sp/billing/wap/12|wc -w         
echo "160042	加载帐单_SP_GSM         ldrmain_sp_gsm_stat     :\t\c"; l /data3/center/data/daystat/output/sp/billing/gsm/6|wc -w          
echo "160052	加载帐单_营业帐单       ldrmain_user_bill_stat  :\t\c"; l /data3/center/data/stat/statoutput/sp/bill/13|wc -w               
echo "160062	加载帐单_梦网稽核       ldrmain_mcas_sms_stat   :\t\c"; l /data3/center/data/settle/output/sp/dream|wc -w                   
echo "160072	加载账单_SP_KJAVA       ldrmain_sp_kjava_stat   :\t\c"; l /data3/center/data/daystat/output/sp/billing/kjava/16|wc -w       
echo "160412	加载帐单_网间_短信      ldr_stat_sms            :\t\c"; l /data2/wj/center/data/daydataloader/input/wj/sms/4|wc -w          
echo "160452	加载帐单_网间_华为      ldr_stat_huawei         :\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/huawei/2|wc -w 
echo "160454	加载帐单_网间_诺基亚    ldr_stat_nokia          :\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/nokia/2|wc -w  
echo "160456	加载帐单_网间_阿尔卡特  ldr_stat_alcatel        :\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/alcatel/2|wc -w
echo "160612	加载帐单_省际_GPRS      ldrmain_stat_roam_gprs  :\t\c"; l /data3/center/data/daydataloader/input/roam/gprs/20|wc -w         
echo "160622	加载帐单_省际_KJAVA     ldrmain_stat_roam_kjava :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/kjava/22|wc -w     
echo "160632	加载帐单_省际_MMS       ldrmain_stat_roam_mms   :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/mms/24|wc -w       
echo "160642	加载帐单_省际_WAP       ldrmain_stat_roam_wap   :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/wap/26|wc -w       
echo "160652	加载帐单_省际_短信      ldrmain_stat_roam_sms   :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/sms/28|wc -w       
echo "160662	加载帐单_省际_小额支付  ldrmain_stat_roam_nmpp  :\t\c"; l /data3/center/data/daystat/output/roam/sp/nmpp|wc -w              
echo "160672	加载帐单_省际_STM       ldrmain_stat_roam_stm   :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/stm/46|wc -w       
echo "160682	加载帐单_省际_CRG       ldrmain_stat_roam_crg   :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/crg/64|wc -w       
echo "160692	加载帐单_省际_MP        ldrmain_stat_roam_mp    :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/mp/46|wc -w        
echo "160702	加载帐单_省际_VC        ldrmain_stat_roam_vc    :\t\c"; l /data3/center/data/daydataloader/input/roam/refill/vc/32|wc -w    
echo "160752	加载帐单_省际_IPC       ldrmain_stat_roam_ipcard:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/ipcard/36|wc -w 
echo "160762	加载帐单_省际_PPS       ldrmain_stat_roam_pps   :\t\c"; l /data3/center/data/daydataloader/input/roam/voice/pps/38|wc -w    
echo "160772	加载帐单_省际_音信      ldrmain_stat_roam_rq    :\t\c"; l /data3/center/data/daydataloader/input/roam/voice/rq/40|wc -w     
echo "160783	加载帐单_省际_换机      ldrmain_stat_roam_korea :\t\c"; l /data3/center/data/daydataloader/input/roam/voice/korea/42|wc -w  
echo "160792	加载帐单_省际_语音      ldrmain_stat_roam_voice :\t\c"; l /data3/center/data/daydataloader/input/roam/voice/voice/44|wc -w  
echo "160801	加载_省际_汇总          ldrmain_stat_roam_total :\t\c"; l /data3/center/data/format/output/roam/sum|wc -w                   
echo "170793	加载帐单_省际_梦网短信  ldrmain_stat_roam_ismg  :\t\c"; l /data3/center/data/daydataloader/input/roam/sp/ismg/57|wc -w      