#!/bin/sh
# select 'echo "'||b.module_id||b.module_name, b.module_code, 
# ':\t\c"; l ' || a.param_value || '|wc -w' "MODULE_INFO FILE_NUMBER"
# from sys_module_param_detail a, sys_module b
# where a.param_code = 'inputPath'
# and a.module_id=b.module_id  AND b.module_id not in ('100411', '180002', '120711', '130711', '150711', '160712')
# and module_name not like '加载错单%' and module_name not like '%临时%'
# order by a.module_id, a.param_code;
echo "       /data4/pickup/prov       pickup                  :\t\c"; l /data4/pickup/prov |wc -w
echo "     center/zwjf_scripts/data   fetch_sp_bill_mcas      :\t\c"; l /data1/home/jsusr1/center/zwjf_scripts/data |wc -w 
echo "110011预处理_SP_GSM	prep_sp_gsm	:\t\c"; l /data3/center/data/acquire/output/sp/billing/gsm|wc -w
echo "110021预处理_SP_ISMG_1	prep_sp_ismg_1	:\t\c"; l /data3/center/data/acquire/output/sp/billing/ismg|wc -w
echo "110022预处理_SP_SMS	prep_sp_sms	:\t\c"; l /data3/center/data/acquire/output/sp/billing/sms|wc -w
echo "110031预处理_SP_WAP	prep_sp_wap	:\t\c"; l /data3/center/data/acquire/output/sp/billing/wap|wc -w
echo "110041预处理_SP_MMS_1	prep_sp_mms_1	:\t\c"; l /data3/center/data/acquire/output/sp/billing/mms|wc -w
echo "110042预处理_SP_KJAVA	prep_sp_kjava	:\t\c"; l /data3/center/data/acquire/output/sp/billing/kjava|wc -w
echo "110051预处理_营业帐单	prep_user_bill	:\t\c"; l /data3/center/data/acquire/output/sp/bill|wc -w
echo "110061预处理_梦网稽核	prep_mcas_sms	:\t\c"; l /data3/center/data/acquire/output/sp/dream|wc -w
echo "110411预处理_网间_短信	prep_sms	:\t\c"; l /data2/wj/center/data/acquire/output/wj/sms|wc -w
echo "110451预处理_网间_华为	prep_hw	:\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/huawei|wc -w
echo "110452预处理_网间_诺基亚	prep_nokia	:\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/nokia|wc -w
echo "110453预处理_网间_阿尔卡特	prep_alcatel	:\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/alcatel|wc -w
echo "110454预处理_网间_华为_temp	prep_hw2	:\t\c"; l /data2/wj/center/data/acquire/output/wj/voice/huawei/temp|wc -w
echo "110611预处理_省际_GPRS	prep_roam_gprs	:\t\c"; l /data3/center/data/acquire/output/roam/gprs|wc -w
echo "110612预处理_省际_CNG	prep_roam_cng	:\t\c"; l /data3/center/data/acquire/output/roam/cng|wc -w
echo "110621预处理_省际_KJAVA	prep_roam_kjava	:\t\c"; l /data3/center/data/acquire/output/roam/sp/kjava|wc -w
echo "110631预处理_省际_MMS	prep_roam_mms	:\t\c"; l /data3/center/data/acquire/output/roam/sp/mms|wc -w
echo "110641预处理_省际_WAP	prep_roam_wap	:\t\c"; l /data3/center/data/acquire/output/roam/sp/wap|wc -w
echo "110651预处理_省际_短信	prep_roam_sms	:\t\c"; l /data3/center/data/acquire/output/roam/sp/sms|wc -w
echo "110661预处理_省际_小额支付	prep_roam_nmpp	:\t\c"; l /data3/center/data/acquire/output/roam/sp/nmpp|wc -w
echo "110671预处理_省际_STM	prep_roam_stm	:\t\c"; l /data3/center/data/acquire/output/roam/sp/stm|wc -w
echo "110681预处理_省际_CRG	prep_roam_crg	:\t\c"; l /data3/center/data/acquire/output/roam/sp/crg|wc -w
echo "110691预处理_省际_MP	prep_roam_mp	:\t\c"; l /data3/center/data/acquire/output/roam/sp/mp|wc -w
echo "110701预处理_省际_VC	prep_roam_vc	:\t\c"; l /data3/center/data/acquire/output/roam/refill/vc|wc -w
echo "110711预处理_省际_SM	prep_roam_sm	:\t\c"; l /data3/center/data/acquire/output/roam/sp/sm|wc -w
echo "110751预处理_省际_IPC	prep_roam_ipcard	:\t\c"; l /data3/center/data/acquire/output/roam/voice/ipcard|wc -w
echo "110761预处理_省际_PPS	prep_roam_pps	:\t\c"; l /data3/center/data/acquire/output/roam/voice/pps|wc -w
echo "110771预处理_省际_音信	prep_roam_rq	:\t\c"; l /data3/center/data/acquire/output/roam/voice/rq|wc -w
echo "110781预处理_省际_换机	prep_roam_korea	:\t\c"; l /data3/center/data/acquire/output/roam/voice/korea|wc -w
echo "110791预处理_省际_语音	prep_roam_voice	:\t\c"; l /data3/center/data/acquire/output/roam/voice/voice|wc -w
echo "110792预处理_省际_语音2	prep_roam_voice2	:\t\c"; l /data3/center/data/acquire/output/roam/voice/voice/2|wc -w
echo "110793预处理_省际_语音3	prep_roam_voice3	:\t\c"; l /data3/center/data/acquire/output/roam/voice/voice/3|wc -w
echo "110801预处理_省际_汇总	prep_roam_sum	:\t\c"; l /data3/center/data/acquire/output/roam/sum|wc -w
echo "110802预处理_省际_汇总2	prep_roam_sum2	:\t\c"; l /data3/center/data/acquire/output/roam/sum2|wc -w
echo "110803预处理_省际_梦网短信	prep_roam_ismg	:\t\c"; l /data3/center/data/acquire/output/roam/sp/ismg|wc -w
echo "110805预处理_省际_CG	prep_roam_cg	:\t\c"; l /data3/center/data/acquire/output/roam/cg|wc -w
echo "110808预处理_网间_MSG	prep_wj_msg	:\t\c"; l /data3/center/data/acquire/output/roam/rmm|wc -w
echo "110815预处理_省际_MTHUS	prep_roam_mthus	:\t\c"; l /data3/center/data/acquire/output/roam/sp/mthus|wc -w
echo "110816预处理_省际_DKXF	prep_roam_dkxf	:\t\c"; l /data3/center/data/acquire/output/roam/sp/dkxf|wc -w
echo "110817预处理_省际_WLAN	prep_roam_wlan	:\t\c"; l /data3/center/data/acquire/output/roam/sp/wlan|wc -w
echo "110818预处理_省际_CGN	prep_roam_cgn	:\t\c"; l /data3/center/data/acquire/output/roam/cgn|wc -w
echo "110819预处理_SP_ISMG_2	prep_sp_ismg_2	:\t\c"; l /data3/center/data/acquire/output/sp/billing/ismg2|wc -w
echo "110820预处理_SP_ISMG_3	prep_sp_ismg_3	:\t\c"; l /data3/center/data/acquire/output/sp/billing/ismg3|wc -w
echo "110821预处理_SP_ISMG_4	prep_sp_ismg_4	:\t\c"; l /data3/center/data/acquire/output/sp/billing/ismg4|wc -w
echo "110822预处理_SP_MMS_2	prep_sp_mms_2	:\t\c"; l /data3/center/data/acquire/output/sp/billing/mms2|wc -w
echo "110823预处理_SP_MMS_3	prep_sp_mms_3	:\t\c"; l /data3/center/data/acquire/output/sp/billing/mms3|wc -w
echo "110824预处理_SP_MMS_4	prep_sp_mms_4	:\t\c"; l /data3/center/data/acquire/output/sp/billing/mms4|wc -w
echo "110825预处理_省际_MTHUS2	prep_roam_mthus2	:\t\c"; l /data3/center/data/acquire/output/roam/sp/mthus2|wc -w
echo "120011分析_SP_GSM	settle_sp_gsm	:\t\c"; l /data3/center/data/format/output/sp/billing/gsm|wc -w
echo "120021分析_SP_ISMG1	settle_sp_ismg1	:\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w
echo "120022分析_SP_ISMG2	settle_sp_ismg2	:\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w
echo "120023分析_SP_ISMG3	settle_sp_ismg3	:\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w
echo "120024分析_SP_ISMG4	settle_sp_ismg4	:\t\c"; l /data3/center/data/format/output/sp/billing/ismg|wc -w
echo "120031分析_SP_MMS	settle_sp_mms	:\t\c"; l /data3/center/data/format/output/sp/billing/mms|wc -w
echo "120032分析_SP_MMS2	settle_sp_mms2	:\t\c"; l /data3/center/data/format/output/sp/billing/mms2|wc -w
echo "120033分析_SP_MMS3	settle_sp_mms3	:\t\c"; l /data3/center/data/format/output/sp/billing/mms3|wc -w
echo "120041分析_SP_WAP	settle_sp_wap	:\t\c"; l /data3/center/data/format/output/sp/billing/wap|wc -w
echo "120042分析_SP_KJAVA	settle_sp_kjava	:\t\c"; l /data3/center/data/format/output/sp/billing/kjava|wc -w
echo "120051分析_营业帐单	settle_user_bill	:\t\c"; l /data3/center/data/format/output/sp/bill|wc -w
echo "120061分析_梦网稽核	settle_mcas_sms	:\t\c"; l /data3/center/data/format/output/sp/dream|wc -w
echo "120411分析_网间_短信	settle_sms	:\t\c"; l /data2/wj/center/data/format/output/wj/sms|wc -w
echo "120451分析_网间_华为	settle_hw	:\t\c"; l /data2/wj/center/data/format/output/wj/voice/huawei|wc -w
echo "120452分析_网间_诺基亚	settle_nokia	:\t\c"; l /data2/wj/center/data/format/output/wj/voice/nokia|wc -w
echo "120453分析_网间_阿尔卡特	settle_alcatel	:\t\c"; l /data2/wj/center/data/format/output/wj/voice/alcatel|wc -w
echo "120454分析_网间_阿尔卡特2	settle_alcatel2	:\t\c"; l /data2/wj/center/data/format/output/wj/voice/alcatel|wc -w
echo "120455分析_网间_华为2	settle_hw2	:\t\c"; l /data2/wj/center/data/format/output/wj/voice/huawei|wc -w
echo "120611分析_省际_GPRS	settle_roam_gprs	:\t\c"; l /data3/center/data/format/output/roam/gprs|wc -w
echo "120621分析_省际_KJAVA	settle_roam_kjava	:\t\c"; l /data3/center/data/format/output/roam/sp/kjava|wc -w
echo "120631分析_省际_MMS	settle_roam_mms	:\t\c"; l /data3/center/data/format/output/roam/sp/mms|wc -w
echo "120641分析_省际_WAP	settle_roam_wap	:\t\c"; l /data3/center/data/format/output/roam/sp/wap|wc -w
echo "120651分析_省际_短信	settle_roam_sms	:\t\c"; l /data3/center/data/format/output/roam/sp/sms|wc -w
echo "120661分析_省际_小额支付	settle_roam_nmpp	:\t\c"; l /data3/center/data/format/output/roam/sp/nmpp|wc -w
echo "120671分析_省际_STM	settle_roam_stm	:\t\c"; l /data3/center/data/format/output/roam/sp/stm|wc -w
echo "120681分析_省际_CRG	settle_roam_crg	:\t\c"; l /data3/center/data/format/output/roam/sp/crg|wc -w
echo "120691分析_省际_MP	settle_roam_mp	:\t\c"; l /data3/center/data/format/output/roam/sp/mp|wc -w
echo "120701分析_省际_VC	settle_roam_vc	:\t\c"; l /data3/center/data/format/output/roam/refill/vc|wc -w
echo "120751分析_省际_IPC	settle_roam_ipcard	:\t\c"; l /data3/center/data/format/output/roam/voice/ipcard|wc -w
echo "120761分析_省际_PPS	settle_roam_pps	:\t\c"; l /data3/center/data/format/output/roam/voice/pps|wc -w
echo "120771分析_省际_音信	settle_roam_rq	:\t\c"; l /data3/center/data/format/output/roam/voice/rq|wc -w
echo "120781分析_省际_换机	settle_roam_korea	:\t\c"; l /data3/center/data/format/output/roam/voice/korea|wc -w
echo "120791分析_省际_语音	settle_roam_voice	:\t\c"; l /data3/center/data/format/output/roam/voice/voice|wc -w
echo "120792分析_省际_梦网短信	settle_roam_ismg	:\t\c"; l /data3/center/data/format/output/roam/sp/ismg|wc -w
echo "120793分析_省际_语音3	settle_roam_voice3	:\t\c"; l /data3/center/data/format/output/roam/voice/voice/3|wc -w
echo "120794分析_省际_语音2	settle_roam_voice2	:\t\c"; l /data3/center/data/format/output/roam/voice/voice/2|wc -w
echo "120796分析_省际_CG	settle_roam_cg	:\t\c"; l /data3/center/data/format/output/roam/cg|wc -w
echo "120799分析_网间_MSG	settle_wj_msg	:\t\c"; l /data2/wj/center/data/format/output/wj/msg|wc -w
echo "120805分析_省际_MTHUS	settle_roam_mthus	:\t\c"; l /data3/center/data/format/output/roam/sp/mthus|wc -w
echo "130011汇总_SP_GSM	stat_sp_gsm	:\t\c"; l /data3/center/data/settle/output/sp/billing/gsm|wc -w
echo "130021汇总_SP_ISMG1	stat_sp_ismg1	:\t\c"; l /data3/center/data/settle/output/sp/billing/ismg|wc -w
echo "130023汇总_SP_ISMG2	stat_sp_ismg2	:\t\c"; l /data3/center/data/settle/output/sp/billing/ismg|wc -w
echo "130031汇总_SP_MMS	stat_sp_mms	:\t\c"; l /data3/center/data/settle/output/sp/billing/mms|wc -w
echo "130041汇总_SP_WAP	stat_sp_wap	:\t\c"; l /data3/center/data/settle/output/sp/billing/wap|wc -w
echo "130042汇总_SP_KJAVA	stat_sp_kjava	:\t\c"; l /data3/center/data/settle/output/sp/billing/kjava|wc -w
echo "130051汇总_营业帐单	stat_user_bill	:\t\c"; l /data3/center/data/settle/output/sp/bill|wc -w
echo "130411汇总_网间_短信	stat_sms	:\t\c"; l /data2/wj/center/data/settle/output/wj/sms|wc -w
echo "130451汇总_网间_华为	stat_hw	:\t\c"; l /data2/wj/center/data/settle/output/wj/voice/huawei|wc -w
echo "130453汇总_网间_诺基亚	stat_nokia	:\t\c"; l /data2/wj/center/data/settle/output/wj/voice/nokia|wc -w
echo "130455汇总_网间_阿尔卡特	stat_alcatel	:\t\c"; l /data2/wj/center/data/settle/output/wj/voice/alcatel|wc -w
echo "130611汇总_省际_GPRS	stat_roam_gprs	:\t\c"; l /data3/center/data/settle/output/roam/gprs|wc -w
echo "130621汇总_省际_KJAVA	stat_roam_kjava	:\t\c"; l /data3/center/data/settle/output/roam/sp/kjava|wc -w
echo "130631汇总_省际_MMS	stat_roam_mms	:\t\c"; l /data3/center/data/settle/output/roam/sp/mms|wc -w
echo "130641汇总_省际_WAP	stat_roam_wap	:\t\c"; l /data3/center/data/settle/output/roam/sp/wap|wc -w
echo "130651汇总_省际_短信	stat_roam_sms	:\t\c"; l /data3/center/data/settle/output/roam/sp/sms|wc -w
echo "130661汇总_省际_小额支付	stat_roam_nmpp	:\t\c"; l /data3/center/data/settle/output/roam/sp/nmpp|wc -w
echo "130671汇总_省际_STM	stat_roam_stm	:\t\c"; l /data3/center/data/settle/output/roam/sp/stm|wc -w
echo "130681汇总_省际_CRG	stat_roam_crg	:\t\c"; l /data3/center/data/settle/output/roam/sp/crg|wc -w
echo "130691汇总_省际_MP	stat_roam_mp	:\t\c"; l /data3/center/data/settle/output/roam/sp/mp|wc -w
echo "130701汇总_省际_VC充值	stat_roam_vc	:\t\c"; l /data3/center/data/settle/output/roam/refill/vc|wc -w
echo "130751汇总_省际_IP记帐卡	stat_roam_ipcard	:\t\c"; l /data3/center/data/settle/output/roam/voice/ipcard|wc -w
echo "130761汇总_省际_PPS	stat_roam_pps	:\t\c"; l /data3/center/data/settle/output/roam/voice/pps|wc -w
echo "130771汇总_省际_音信	stat_roam_rq	:\t\c"; l /data3/center/data/settle/output/roam/voice/rq|wc -w
echo "130781汇总_省际_换机	stat_roam_korea	:\t\c"; l /data3/center/data/settle/output/roam/voice/korea|wc -w
echo "130791汇总_省际_语音	stat_roam_voice	:\t\c"; l /data3/center/data/settle/output/roam/voice/voice|wc -w
echo "130792汇总_省际_梦网短信	stat_roam_ismg	:\t\c"; l /data3/center/data/settle/output/roam/sp/ismg|wc -w
echo "130793汇总_网间_MSG	stat_wj_msg	:\t\c"; l /data2/wj/center/data/settle/output/wj/msg|wc -w
echo "130797汇总_省际_MTHUS	stat_roam_mthus	:\t\c"; l /data3/center/data/settle/output/roam/sp/mthus|wc -w
echo "140012日汇总_SP_GSM	daystat_sp_gsm	:\t\c"; l /data3/center/data/stat/statoutput/sp/billing/gsm/5|wc -w
echo "140022日汇总_SP_ISMG	daystat_sp_ismg	:\t\c"; l /data3/center/data/stat/statoutput/sp/billing/ismg/7|wc -w
echo "140032日汇总_SP_MMS	daystat_sp_mms	:\t\c"; l /data3/center/data/stat/statoutput/sp/billing/mms/9|wc -w
echo "140042日汇总_SP_WAP	daystat_sp_wap	:\t\c"; l /data3/center/data/stat/statoutput/sp/billing/wap/11|wc -w
echo "140072日汇总_SP_KJAVA	daystat_sp_kjava	:\t\c"; l /data3/center/data/stat/statoutput/sp/billing/kjava/15|wc -w
echo "140412日汇总_网间_短信	daystat_sms	:\t\c"; l /data2/wj/center/data/stat/statoutput/wj/sms/3|wc -w
echo "140452日汇总_网间_华为	daystat_hw	:\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/huawei/1|wc -w
echo "140454日汇总_网间_诺基亚	daystat_nokia	:\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/nokia/1|wc -w
echo "140455日汇总_网间_彩信	daystat_msg	:\t\c"; l /data2/wj/center/data/stat/statoutput/wj/msg/104|wc -w
echo "140456日汇总_网间_阿尔卡特	daystat_alcatel	:\t\c"; l /data2/wj/center/data/stat/statoutput/wj/voice/alcatel/1|wc -w
echo "150011加载清单_SP_GSM	ldrmain_sp_gsm	:\t\c"; l /data3/center/back/stat/output/sp/billing/gsm|wc -w
echo "150021加载清单_SP_ISMG	ldrmain_sp_ismg	:\t\c"; l /data3/center/back/stat/output/sp/billing/ismg|wc -w
echo "150031加载清单_SP_MMS	ldrmain_sp_mms	:\t\c"; l /data3/center/back/stat/output/sp/billing/mms|wc -w
echo "150041加载清单_SP_WAP	ldrmain_sp_wap	:\t\c"; l /data3/center/back/stat/output/sp/billing/wap|wc -w
echo "150042加载清单_SP_KJAVA	ldrmain_sp_kjava	:\t\c"; l /data3/center/data/stat/output/sp/billing/kjava|wc -w
echo "150051加载清单_营业帐单	ldrmain_user_bill	:\t\c"; l /data3/center/back/stat/output/sp/bill|wc -w
echo "150411加载清单_网间_短信	ldrmain_sms_data	:\t\c"; l /data2/wj/center/back/stat/output/wj/sms|wc -w
echo "150451加载清单_网间_华为	ldr_huawei	:\t\c"; l /data2/wj/center/back/stat/output/wj/voice/huawei|wc -w
echo "150453加载清单_网间_诺基亚	ldr_nokia	:\t\c"; l /data2/wj/center/back/stat/output/wj/voice/nokia|wc -w
echo "150455加载清单_网间_阿尔卡特	ldr_alcatel	:\t\c"; l /data2/wj/center/back/stat/output/wj/voice/alcatel|wc -w
echo "150456加载清单_网间_阿尔卡特2	ldr_alcatel2	:\t\c"; l /data2/wj/center/back/stat/output/wj/voice/alcatel|wc -w
echo "150611加载清单_省际_GPRS	ldrmain_roam_gprs	:\t\c"; l /data3/center/back/stat/output/roam/gprs|wc -w
echo "150621加载清单_省际_KJAVA	ldrmain_roam_kjava	:\t\c"; l /data3/center/back/stat/output/roam/sp/kjava|wc -w
echo "150631加载清单_省际_MMS	ldrmain_roam_mms	:\t\c"; l /data3/center/back/stat/output/roam/sp/mms|wc -w
echo "150641加载清单_省际_WAP	ldrmain_roam_wap	:\t\c"; l /data3/center/back/stat/output/roam/sp/wap|wc -w
echo "150651加载清单_省际_短信	ldrmain_roam_sms	:\t\c"; l /data3/center/back/stat/output/roam/sp/sms|wc -w
echo "150661加载清单_省际_小额支付	ldrmain_roam_nmpp	:\t\c"; l /data3/center/data/dataloader/output/roam/sp/nmpp|wc -w
echo "150671加载清单_省际_STM	ldrmain_roam_stm	:\t\c"; l /data3/center/back/stat/output/roam/sp/stm|wc -w
echo "150681加载清单_省际_CRG	ldrmain_roam_crg	:\t\c"; l /data3/center/back/stat/output/roam/sp/crg|wc -w
echo "150691加载清单_省际_MP	ldrmain_roam_mp	:\t\c"; l /data3/center/back/stat/output/roam/sp/mp|wc -w
echo "150701加载清单_省际_VC	ldrmain_roam_vc	:\t\c"; l /data3/center/back/stat/output/roam/refill/vc|wc -w
echo "150751加载清单_省际_IPC	ldrmain_roam_ipcard	:\t\c"; l /data3/center/data/dataloader/output/roam/voice/ipcard|wc -w
echo "150761加载清单_省际_PPS	ldrmain_roam_pps	:\t\c"; l /data3/center/back/stat/output/roam/voice/pps|wc -w
echo "150771加载清单_省际_音信	ldrmain_roam_rq	:\t\c"; l /data3/center/back/stat/output/roam/voice/rq|wc -w
echo "150781加载清单_省际_换机	ldrmain_roam_korea	:\t\c"; l /data3/center/data/stat/output/roam/voice/korea|wc -w
echo "150791加载清单_省际_语音	ldrmain_roam_voice	:\t\c"; l /data3/center/back/stat/output/roam/voice/voice|wc -w
echo "150794加载清单_省际_梦网短信	ldrmain_roam_ismg	:\t\c"; l /data3/center/back/stat/output/roam/sp/ismg|wc -w
echo "150795加载清单_网间_彩信	ldr_wj_msg	:\t\c"; l /data2/wj/center/back/stat/output/wj/msg|wc -w
echo "150802加载清单_省际_MTHUS	ldrmain_roam_mthus	:\t\c"; l /data3/center/back/stat/output/roam/sp/mthus|wc -w
echo "150803加载清单_省际_DKXF	ldrmain_roam_dkxf	:\t\c"; l /data3/center/data/format/output/roam/sp/dkxf|wc -w
echo "150804加载清单_省际_WLAN	ldrmain_roam_wlan	:\t\c"; l /data3/center/data/format/output/roam/sp/wlan|wc -w
echo "150805加载清单_省际_MTHUS2	ldrmain_roam_mthus2	:\t\c"; l /data3/center/data/format/output/roam/sp/mthus2|wc -w
echo "160012加载帐单_SP_ISMG	ldrmain_sp_ismg_stat	:\t\c"; l /data3/center/data/daystat/output/sp/billing/ismg/8|wc -w
echo "160022加载帐单_SP_MMS	ldrmain_sp_mms_stat	:\t\c"; l /data3/center/data/daystat/output/sp/billing/mms/10|wc -w
echo "160032加载帐单_SP_WAP	ldrmain_sp_wap_stat	:\t\c"; l /data3/center/data/daystat/output/sp/billing/wap/12|wc -w
echo "160042加载帐单_SP_GSM	ldrmain_sp_gsm_stat	:\t\c"; l /data3/center/data/daystat/output/sp/billing/gsm/6|wc -w
echo "160052加载帐单_营业帐单	ldrmain_user_bill_stat	:\t\c"; l /data3/center/data/stat/statoutput/sp/bill/13|wc -w
echo "160062加载帐单_梦网稽核	ldrmain_mcas_sms_stat	:\t\c"; l /data3/center/data/settle/output/sp/dream|wc -w
echo "160072加载账单_SP_KJAVA	ldrmain_sp_kjava_stat	:\t\c"; l /data3/center/data/daystat/output/sp/billing/kjava/16|wc -w
echo "160412加载帐单_网间_短信	ldr_stat_sms	:\t\c"; l /data2/wj/center/data/daydataloader/input/wj/sms/4|wc -w
echo "160452加载帐单_网间_华为	ldr_stat_huawei	:\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/huawei/2|wc -w
echo "160454加载帐单_网间_诺基亚	ldr_stat_nokia	:\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/nokia/2|wc -w
echo "160456加载帐单_网间_阿尔卡特	ldr_stat_alcatel	:\t\c"; l /data2/wj/center/data/daydataloader/input/wj/voice/alcatel/2|wc -w
echo "160612加载帐单_省际_GPRS	ldrmain_stat_roam_gprs	:\t\c"; l /data3/center/data/daydataloader/input/roam/gprs/20|wc -w
echo "160622加载帐单_省际_KJAVA	ldrmain_stat_roam_kjava	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/kjava/22|wc -w
echo "160632加载帐单_省际_MMS	ldrmain_stat_roam_mms	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/mms/24|wc -w
echo "160642加载帐单_省际_WAP	ldrmain_stat_roam_wap	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/wap/26|wc -w
echo "160652加载帐单_省际_短信	ldrmain_stat_roam_sms	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/sms/28|wc -w
echo "160662加载帐单_省际_小额支付	ldrmain_stat_roam_nmpp	:\t\c"; l /data3/center/data/daystat/output/roam/sp/nmpp|wc -w
echo "160672加载帐单_省际_STM	ldrmain_stat_roam_stm	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/stm/46|wc -w
echo "160682加载帐单_省际_CRG	ldrmain_stat_roam_crg	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/crg/64|wc -w
echo "160692加载帐单_省际_MP	ldrmain_stat_roam_mp	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/mp/46|wc -w
echo "160702加载帐单_省际_VC	ldrmain_stat_roam_vc	:\t\c"; l /data3/center/data/daydataloader/input/roam/refill/vc/32|wc -w
echo "160752加载帐单_省际_IPC	ldrmain_stat_roam_ipcard	:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/ipcard/36|wc -w
echo "160762加载帐单_省际_PPS	ldrmain_stat_roam_pps	:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/pps/38|wc -w
echo "160772加载帐单_省际_音信	ldrmain_stat_roam_rq	:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/rq/40|wc -w
echo "160783加载帐单_省际_换机	ldrmain_stat_roam_korea	:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/korea/42|wc -w
echo "160792加载帐单_省际_语音	ldrmain_stat_roam_voice	:\t\c"; l /data3/center/data/daydataloader/input/roam/voice/voice/44|wc -w
echo "160801加载_省际_汇总	ldrmain_stat_roam_total	:\t\c"; l /data3/center/data/format/output/roam/sum|wc -w
echo "170793加载帐单_省际_梦网短信	ldrmain_stat_roam_ismg	:\t\c"; l /data3/center/data/daydataloader/input/roam/sp/ismg/57|wc -w
echo "170794加载帐单_网间_彩信	ldr_stat_msg	:\t\c"; l /data2/wj/center/data/daydataloader/input/wj/msg/105|wc -w
echo "170798加载分销_用户数据	ldrmain_fenxiao_user	:\t\c"; l /data3/center/data/acquire/output/roam/sp/fenxiaouser|wc -w
echo "110814预处理_SP_IIM	prep_sp_iim	:\t\c"; l /data3/center/data/acquire/output/roam/sp/iim|wc -w
echo "120804分析_SP_IIM	settle_sp_iim	:\t\c"; l /data3/center/data/format/output/sp/billing/iim|wc -w
echo "130796汇总_SP_IIM	stat_sp_iim	:\t\c"; l /data3/center/data/settle/output/sp/billing/iim|wc -w
echo "170797加载帐单_SP_IIM     ldrmain_sp_iim_stat     :\t\c"; l /data3/center/data/stat/output/sp/billing/iim/109|wc -w

