echo "汇总_SP_ISMG1               :/data3/center/error/stat/sp/billing/ismg                     :\t\c";l /data3/center/error/stat/sp/billing/ismg|wc -w
echo "汇总_SP_WAP                 :/data3/center/error/stat/sp/billing/wap                      :\t\c";l /data3/center/error/stat/sp/billing/wap|wc -w
echo "汇总_SP_ISMG2               :/data3/center/error/stat/sp/billing/ismg                     :\t\c";l /data3/center/error/stat/sp/billing/ismg|wc -w
echo "日汇总_SP_ISMG              :/data3/center/error/daystat/sp/billing/ismg                  :\t\c";l /data3/center/error/daystat/sp/billing/ismg|wc -w
echo "日汇总_SP_MMS               :/data3/center/error/daystat/sp/billing/mms                   :\t\c";l /data3/center/error/daystat/sp/billing/mms|wc -w
#echo "分析_SP_GSM                 :/data3/center/error/settle/sp/billing/gsm                    :\t\c";l /data3/center/error/settle/sp/billing/gsm|wc -w
echo "预处理_SP_ISMG              :/data3/center/error/format/sp/billing/ismg                   :\t\c";l /data3/center/error/format/sp/billing/ismg|wc -w
echo "预处理_SP_KJAVA             :/data3/center/error/format/sp/billing/kjava                  :\t\c";l /data3/center/error/format/sp/billing/kjava|wc -w
echo "分析_网间_短信              :/data2/wj/center/error/settle/wj/sms                         :\t\c";l /data2/wj/center/error/settle/wj/sms|wc -w
echo "预处理_SP_GSM               :/data3/center/error/format/sp/billing/gsm                    :\t\c";l /data3/center/error/format/sp/billing/gsm|wc -w
echo "预处理_SP_SMS               :/data3/center/error/format/sp/billing/ismg                   :\t\c";l /data3/center/error/format/sp/billing/ismg|wc -w
echo "预处理_SP_WAP               :/data3/center/error/format/sp/billing/wap                    :\t\c";l /data3/center/error/format/sp/billing/wap|wc -w
echo "预处理_SP_MMS               :/data3/center/error/format/sp/billing/mms                    :\t\c";l /data3/center/error/format/sp/billing/mms|wc -w
echo "分析_SP_ISMG1               :/data3/center/error/settle/sp/billing/ismg                   :\t\c";l /data3/center/error/settle/sp/billing/ismg|wc -w
echo "分析_SP_ISMG2               :/data3/center/error/settle/sp/billing/ismg                   :\t\c";l /data3/center/error/settle/sp/billing/ismg|wc -w
echo "分析_SP_ISMG4               :/data3/center/error/settle/sp/billing/ismg                   :\t\c";l /data3/center/error/settle/sp/billing/ismg|wc -w
#echo "预处理_网间_阿尔卡特        :/data2/wj/center/error/format/wj/voice/alcatel               :\t\c";l /data2/wj/center/error/format/wj/voice/alcatel|wc -w
echo "分析_SP_ISMG3               :/data3/center/error/settle/sp/billing/ismg                   :\t\c";l /data3/center/error/settle/sp/billing/ismg|wc -w
echo "预处理_网间_MSG             :/data2/wj/center/error/format/wj/msg                         :\t\c";l /data2/wj/center/error/format/wj/msg|wc -w
#echo "分析_网间_华为              :/data2/wj/center/error/settle/wj/voice/huawei                :\t\c";l /data2/wj/center/error/settle/wj/voice/huawei|wc -w
#echo "分析_网间_诺基亚            :/data2/wj/center/error/settle/wj/voice/nokia                 :\t\c";l /data2/wj/center/error/settle/wj/voice/nokia|wc -w
#echo "加载错单_网间_华为          :/data2/wj/center/error/dataloader/wj/voice/huawei            :\t\c";l /data2/wj/center/error/dataloader/wj/voice/huawei|wc -w
#echo "分析_网间_阿尔卡特          :/data2/wj/center/error/settle/wj/voice/alcatel               :\t\c";l /data2/wj/center/error/settle/wj/voice/alcatel|wc -w
#echo "分析_网间_阿尔卡特2         :/data2/wj/center/error/settle/wj/voice/alcatel               :\t\c";l /data2/wj/center/error/settle/wj/voice/alcatel|wc -w
echo "日汇总_网间_华为            :/data2/wj/center/error/daystat/wj/voice/huawei               :\t\c";l /data2/wj/center/error/daystat/wj/voice/huawei|wc -w
echo "日汇总_网间_诺基亚          :/data2/wj/center/error/daystat/wj/voice/nokia                :\t\c";l /data2/wj/center/error/daystat/wj/voice/nokia|wc -w
echo "日汇总_SP_KJAVA             :/data3/center/error/daystat/sp/billing/kjava                 :\t\c";l /data3/center/error/daystat/sp/billing/kjava|wc -w
echo "日汇总_网间_阿尔卡特        :/data2/wj/center/error/daystat/wj/voice/alcatel              :\t\c";l /data2/wj/center/error/daystat/wj/voice/alcatel|wc -w
echo "日汇总_SP_WAP               :/data3/center/error/daystat/sp/billing/wap                   :\t\c";l /data3/center/error/daystat/sp/billing/wap|wc -w
echo "汇总_SP_KJAVA               :/data3/center/error/stat/sp/billing/kjava                    :\t\c";l /data3/center/error/stat/sp/billing/kjava|wc -w
#echo "分析_网间_华为2             :/data2/wj/center/error/settle/wj/voice/huawei                :\t\c";l /data2/wj/center/error/settle/wj/voice/huawei|wc -w
#echo "加载错单_网间_阿尔卡特      :/data2/wj/center/error/dataloader/wj/voice/alcatel           :\t\c";l /data2/wj/center/error/dataloader/wj/voice/alcatel|wc -w
echo "汇总_SP_GSM                 :/data3/center/error/stat/sp/billing/gsm                      :\t\c";l /data3/center/error/stat/sp/billing/gsm|wc -w
echo "汇总_SP_MMS                 :/data3/center/error/stat/sp/billing/mms                      :\t\c";l /data3/center/error/stat/sp/billing/mms|wc -w
echo "汇总_网间_华为              :/data2/wj/center/error/stat/wj/voice/huawei                  :\t\c";l /data2/wj/center/error/stat/wj/voice/huawei|wc -w
echo "汇总_网间_诺基亚            :/data2/wj/center/error/stat/wj/voice/nokia                   :\t\c";l /data2/wj/center/error/stat/wj/voice/nokia|wc -w
echo "加载帐单_网间_短信          :/data2/wj/center/error/daydataloader/wj/sms                  :\t\c";l /data2/wj/center/error/daydataloader/wj/sms|wc -w
echo "汇总_网间_阿尔卡特          :/data2/wj/center/error/stat/wj/voice/alcatel                 :\t\c";l /data2/wj/center/error/stat/wj/voice/alcatel|wc -w
#echo "加载清单_网间_诺基亚        :/data2/wj/center/error/dataloader/wj/voice/nokia             :\t\c";l /data2/wj/center/error/dataloader/wj/voice/nokia|wc -w
#echo "预处理_网间_华为_temp       :/data2/wj/center/error/format/wj/voice/huawei                :\t\c";l /data2/wj/center/error/format/wj/voice/huawei|wc -w
echo "分析_SP_MMS                 :/data3/center/error/settle/sp/billing/mms                    :\t\c";l /data3/center/error/settle/sp/billing/mms|wc -w
echo "日汇总_网间_短信            :/data2/wj/center/error/daystat/wj/sms                        :\t\c";l /data2/wj/center/error/daystat/wj/sms|wc -w
echo "分析_SP_WAP                 :/data3/center/error/settle/sp/billing/wap                    :\t\c";l /data3/center/error/settle/sp/billing/wap|wc -w
echo "日汇总_网间_彩信            :/data2/wj/center/error/daystat/wj/msg                        :\t\c";l /data2/wj/center/error/daystat/wj/msg|wc -w
echo "汇总_网间_MSG               :/data2/wj/center/error/stat/wj/msg                           :\t\c";l /data2/wj/center/error/stat/wj/msg|wc -w
echo "加载帐单_网间_彩信          :/data2/wj/center/error/daydataloader/wj/msg                  :\t\c";l /data2/wj/center/error/daydataloader/wj/msg|wc -w
#echo "加载清单_网间_短信          :/data2/wj/center/error/dataloader/wj/sms                     :\t\c";l /data2/wj/center/error/dataloader/wj/sms|wc -w
echo "分析_网间_MSG               :/data2/wj/center/error/settle/wj/msg                         :\t\c";l /data2/wj/center/error/settle/wj/msg|wc -w
echo "加载帐单_SP_ISMG            :/data3/center/error/daydataloader/sp/billing/ismg            :\t\c";l /data3/center/error/daydataloader/sp/billing/ismg|wc -w
echo "加载帐单_SP_MMS             :/data3/center/error/daydataloader/sp/billing/mms             :\t\c";l /data3/center/error/daydataloader/sp/billing/mms|wc -w
echo "加载帐单_SP_GSM             :/data3/center/error/daydataloader/sp/billing/gsm             :\t\c";l /data3/center/error/daydataloader/sp/billing/gsm|wc -w
#echo "加载清单_网间_华为          :/data2/wj/center/error/dataloader/wj/voice/huawei            :\t\c";l /data2/wj/center/error/dataloader/wj/voice/huawei|wc -w
echo "加载账单_SP_KJAVA           :/data3/center/error/daydataloader/sp/billing/kjava           :\t\c";l /data3/center/error/daydataloader/sp/billing/kjava|wc -w
echo "加载清单_SP_KJAVA           :/data3/center/error/dataloader/sp/billing/kjava              :\t\c";l /data3/center/error/dataloader/sp/billing/kjava|wc -w
echo "汇总_网间_短信              :/data2/wj/center/error/stat/wj/sms                           :\t\c";l /data2/wj/center/error/stat/wj/sms|wc -w
echo "日汇总_SP_GSM               :/data3/center/error/daystat/sp/billing/gsm                   :\t\c";l /data3/center/error/daystat/sp/billing/gsm|wc -w
echo "分析_SP_KJAVA               :/data3/center/error/settle/sp/billing/kjava                  :\t\c";l /data3/center/error/settle/sp/billing/kjava|wc -w
echo "加载帐单_SP_WAP             :/data3/center/error/daydataloader/sp/billing/wap             :\t\c";l /data3/center/error/daydataloader/sp/billing/wap|wc -w
echo "加载帐单_网间_诺基亚        :/data2/wj/center/error/daydataloader/wj/voice/nokia          :\t\c";l /data2/wj/center/error/daydataloader/wj/voice/nokia|wc -w
echo "加载帐单_网间_阿尔卡特      :/data2/wj/center/error/daydataloader/wj/voice/alcatel        :\t\c";l /data2/wj/center/error/daydataloader/wj/voice/alcatel|wc -w
echo "预处理_网间_诺基亚          :/data2/wj/center/error/format/wj/voice/nokia                 :\t\c";l /data2/wj/center/error/format/wj/voice/nokia|wc -w
echo "加载清单_SP_MMS             :/data3/center/error/dataloader/sp/billing/mms                :\t\c";l /data3/center/error/dataloader/sp/billing/mms|wc -w
echo "加载清单_SP_WAP             :/data3/center/error/dataloader/sp/billing/wap                :\t\c";l /data3/center/error/dataloader/sp/billing/wap|wc -w
echo "加载清单_SP_GSM             :/data3/center/error/dataloader/sp/billing/gsm                :\t\c";l /data3/center/error/dataloader/sp/billing/gsm|wc -w
echo "加载清单_SP_ISMG            :/data3/center/error/dataloader/sp/billing/ismg               :\t\c";l /data3/center/error/dataloader/sp/billing/ismg|wc -w
echo "分析_SP_MCBBJ1              :/data3/center/error/settle/sp/billing/mcbbj1                 :\t\c";l /data3/center/error/settle/sp/billing/mcbbj1|wc -w
#echo "预处理_网间_短信            :/data2/wj/center/error/format/wj/sms                         :\t\c";l /data2/wj/center/error/format/wj/sms|wc -w
echo "预处理_SP_MCBBJ1            :/data3/center/error/format/sp/billing/mcbbj1                 :\t\c";l /data3/center/error/format/sp/billing/mcbbj1|wc -w
echo "加载清单_SP_MCBBJ1          :/data3/center/error/dataloader/sp/billing/mcbbj1             :\t\c";l /data3/center/error/dataloader/sp/billing/mcbbj1|wc -w
echo "分析_SP_MCBBJ0              :/data3/center/error/settle/sp/billing/mcbbj0                 :\t\c";l /data3/center/error/settle/sp/billing/mcbbj0|wc -w
echo "预处理_SP_MCBBJ0            :/data3/center/error/format/sp/billing/mcbbj0                 :\t\c";l /data3/center/error/format/sp/billing/mcbbj0|wc -w
echo "分析_SP_MMS2                :/data3/center/error/settle/sp/billing/mms                    :\t\c";l /data3/center/error/settle/sp/billing/mms|wc -w
#echo "加载清单_网间_阿尔卡特      :/data2/wj/center/error/dataloader/wj/voice/alcatel           :\t\c";l /data2/wj/center/error/dataloader/wj/voice/alcatel|wc -w
echo "分析_SP_MMS3                :/data3/center/error/settle/sp/billing/mms                    :\t\c";l /data3/center/error/settle/sp/billing/mms|wc -w
echo "加载清单_SP_MCBBJ0          :/data3/center/error/dataloader/sp/billing/mcbbj0             :\t\c";l /data3/center/error/dataloader/sp/billing/mcbbj0|wc -w
#echo "预处理_网间_华为            :/data2/wj/center/error/format/wj/voice/huawei                :\t\c";l /data2/wj/center/error/format/wj/voice/huawei|wc -w
echo "加载帐单_网间_华为          :/data2/wj/center/error/daydataloader/wj/voice/huawei         :\t\c";l /data2/wj/center/error/daydataloader/wj/voice/huawei|wc -w
