LOAD DATA
INFILE '/data1/home/jsusr1/center/scripts/spdz/SMSZZY/pushresult_20100528225008_01259.TXT'
APPEND INTO TABLE sms_pushresult
FIELDS TERMINATED BY ',' TRAILING NULLCOLS
(
SEND_NUM,
RECEIVE_NUM,
SEND_DATE,
SEND_TYPE,
SEND_REASON,
FEE,
CP_CODE,
CP_NAME "Trim(:CP_NAME)"
)
